steps:
  - label: ':docker: Prepare package.json'
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.3.0:
          run: minimal-packager
    artifact_paths: min_packages.tar

  - wait

  - label: ':docker: Build CI image'
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.2.0:
          download: min_packages.tar
      - docker-compose#v3.3.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base
      - docker-compose#v3.3.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base

  - wait

  - label: 'Trigger React-native pipeline'
    trigger: 'at-bugsnag-react-native'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Lint'
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.3.0:
        run: ci
    command: 'npm run test:lint'

  - label: 'Unit tests'
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.3.0:
        run: ci
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.3.0:
        run: ci
    command: 'npm run test:types'
